import { ActionType } from 'typesafe-actions';
import { notActions } from '@/features';

export type AllActions = ActionType<typeof notActions>;

export enum ActionList {
    NOTIFICATION_LIST_ASYNC_REQUEST = 'NOTIFICATION_LIST_ASYNC_REQUEST',
    NOTIFICATION_LIST_ASYNC_SUCCESS = 'NOTIFICATION_LIST_ASYNC_SUCCESS',
    NOTIFICATION_LIST_ASYNC_FAILURE = 'NOTIFICATION_LIST_ASYNC_FAILURE',
    NOTIFICATION_UPDATE_INFINITE_NOTIFICATION = 'NOTIFICATION_UPDATE_INFINITE_NOTIFICATION',

    NOTIFICATION_CONFIG_ASYNC_REQUEST = 'NOTIFICATION_CONFIG_ASYNC_REQUEST',
    NOTIFICATION_CONFIG_ASYNC_SUCCESS = 'NOTIFICATION_CONFIG_ASYNC_SUCESS',
    NOTIFICATION_CONFIG_ASYNC_FAILURE = 'NOTIFICATION_CONFIG_ASYNC_FAILURE',

    PLACEHOLDER_ASYNC_REQUEST = 'PLACEHOLDER_ASYNC_REQUEST',
    PLACEHOLDER_ASYNC_SUCCESS = 'PLACEHOLDER_ASYNC_SUCCESS',
    PLACEHOLDER_ASYNC_FAILURE = 'PLACEHOLDER_ASYNC_FAILURE',
}